import { Itinerary, TripProfile } from './types';

export const MOCK_TRIP_PROFILE: TripProfile = {
  origin: 'San Francisco',
  destinations: ['Tokyo'],
  startDate: '2026-03-15',
  endDate: '2026-03-18',
  budgetMin: 1500,
  budgetMax: 3000,
  currency: 'USD',
  pace: 'balanced',
  interests: ['foodie', 'culture', 'nightlife'],
  constraints: {
    dietary: [],
    walkingTolerance: 'high',
    mustSeeItems: ['Shibuya Crossing', 'Tsukiji Outer Market'],
    additionalNotes: '',
  },
};

export const MOCK_ITINERARY: Itinerary = {
  id: 'mock-itinerary-001',
  tripProfile: MOCK_TRIP_PROFILE,
  summary: 'A 3-day Tokyo adventure blending traditional culture with modern food scenes and vibrant nightlife. Experience iconic landmarks, hidden local gems, and world-class cuisine.',
  totalEstimatedCost: 2100,
  generatedAt: '2026-03-01T00:00:00.000Z',
  days: [
    {
      dayIndex: 0,
      date: '2026-03-15',
      morningActivities: [
        {
          id: 'act-001',
          name: 'Tsukiji Outer Market Food Tour',
          description: 'Explore the famous outer market with fresh sushi, tamagoyaki, and street food stalls that have been feeding Tokyo for decades.',
          category: 'food',
          neighborhood: 'Tsukiji',
          duration: 120,
          costEstimate: 45,
          tags: ['foodie', 'local', 'must-see'],
          timeOfDay: 'morning',
        },
        {
          id: 'act-002',
          name: 'Hama-rikyu Gardens',
          description: 'A stunning Edo-era garden with a tea house on a tidal pond, perfect for a peaceful morning stroll.',
          category: 'nature',
          neighborhood: 'Shiodome',
          duration: 60,
          costEstimate: 5,
          tags: ['nature', 'culture', 'peaceful'],
          timeOfDay: 'morning',
        },
      ],
      afternoonActivities: [
        {
          id: 'act-003',
          name: 'Senso-ji Temple & Nakamise Street',
          description: 'Tokyo\'s oldest temple with a vibrant shopping street leading up to it. Great for photos and traditional snacks.',
          category: 'culture',
          neighborhood: 'Asakusa',
          duration: 90,
          costEstimate: 10,
          tags: ['culture', 'iconic', 'shopping'],
          timeOfDay: 'afternoon',
        },
        {
          id: 'act-004',
          name: 'Akihabara Electric Town',
          description: 'Dive into Tokyo\'s tech and anime culture district. Browse electronics, retro games, and themed cafes.',
          category: 'activity',
          neighborhood: 'Akihabara',
          duration: 90,
          costEstimate: 30,
          tags: ['culture', 'shopping', 'unique'],
          timeOfDay: 'afternoon',
        },
      ],
      eveningActivities: [
        {
          id: 'act-005',
          name: 'Ramen Tasting at Fuunji',
          description: 'One of Tokyo\'s top-rated tsukemen (dipping ramen) shops in Shinjuku. Expect a short wait but unforgettable noodles.',
          category: 'food',
          neighborhood: 'Shinjuku',
          duration: 45,
          costEstimate: 15,
          tags: ['foodie', 'local', 'budget-friendly'],
          timeOfDay: 'evening',
        },
        {
          id: 'act-006',
          name: 'Golden Gai Bar Hopping',
          description: 'Wander through tiny bars in this legendary alleyway district. Each bar seats 5–10 people with unique themes.',
          category: 'nightlife',
          neighborhood: 'Shinjuku',
          duration: 120,
          costEstimate: 50,
          tags: ['nightlife', 'local', 'unique'],
          timeOfDay: 'evening',
        },
      ],
      dailyBudget: 155,
    },
    {
      dayIndex: 1,
      date: '2026-03-16',
      morningActivities: [
        {
          id: 'act-007',
          name: 'Meiji Jingu Shrine',
          description: 'A serene Shinto shrine set in a lush forest in the heart of the city. Arrive early for a peaceful experience.',
          category: 'culture',
          neighborhood: 'Harajuku',
          duration: 75,
          costEstimate: 0,
          tags: ['culture', 'nature', 'free'],
          timeOfDay: 'morning',
        },
        {
          id: 'act-008',
          name: 'Harajuku & Takeshita Street',
          description: 'Japan\'s youth fashion capital. Colorful crepes, quirky fashion, and people-watching at its finest.',
          category: 'shopping',
          neighborhood: 'Harajuku',
          duration: 60,
          costEstimate: 25,
          tags: ['shopping', 'culture', 'fun'],
          timeOfDay: 'morning',
        },
      ],
      afternoonActivities: [
        {
          id: 'act-009',
          name: 'Shibuya Crossing & Shibuya Sky',
          description: 'Experience the world\'s busiest intersection and then head up to Shibuya Sky for panoramic views of the city.',
          category: 'sight',
          neighborhood: 'Shibuya',
          duration: 90,
          costEstimate: 25,
          tags: ['iconic', 'must-see', 'views'],
          timeOfDay: 'afternoon',
        },
        {
          id: 'act-010',
          name: 'Depachika Food Hall at Shibuya Hikarie',
          description: 'Explore the basement food floors of a Japanese department store. Sample wagashi, bento, and artisan treats.',
          category: 'food',
          neighborhood: 'Shibuya',
          duration: 60,
          costEstimate: 30,
          tags: ['foodie', 'local', 'unique'],
          timeOfDay: 'afternoon',
        },
      ],
      eveningActivities: [
        {
          id: 'act-011',
          name: 'Omakase Dinner at a Local Sushi Counter',
          description: 'Treat yourself to a chef\'s-choice sushi dinner at an intimate counter-style restaurant in Ebisu.',
          category: 'food',
          neighborhood: 'Ebisu',
          duration: 90,
          costEstimate: 120,
          tags: ['foodie', 'premium', 'experience'],
          timeOfDay: 'evening',
        },
        {
          id: 'act-012',
          name: 'Ebisu Yokocho Night Market',
          description: 'A lively indoor food alley with dozens of small stalls serving yakitori, oden, and craft beer.',
          category: 'nightlife',
          neighborhood: 'Ebisu',
          duration: 90,
          costEstimate: 35,
          tags: ['nightlife', 'foodie', 'local'],
          timeOfDay: 'evening',
        },
      ],
      dailyBudget: 235,
    },
    {
      dayIndex: 2,
      date: '2026-03-17',
      morningActivities: [
        {
          id: 'act-013',
          name: 'teamLab Borderless',
          description: 'Immersive digital art museum with mind-bending projections and interactive installations. Book tickets in advance.',
          category: 'culture',
          neighborhood: 'Azabudai',
          duration: 120,
          costEstimate: 35,
          tags: ['culture', 'art', 'unique', 'instagram'],
          timeOfDay: 'morning',
        },
      ],
      afternoonActivities: [
        {
          id: 'act-014',
          name: 'Yanaka Old Town Walking Tour',
          description: 'Explore one of Tokyo\'s best-preserved old neighborhoods with traditional shops, temples, and a nostalgic cat-themed street.',
          category: 'culture',
          neighborhood: 'Yanaka',
          duration: 120,
          costEstimate: 10,
          tags: ['culture', 'local', 'peaceful', 'hidden-gem'],
          timeOfDay: 'afternoon',
        },
        {
          id: 'act-015',
          name: 'Ueno Park & Ameyoko Market',
          description: 'Stroll through the sprawling park, then dive into the chaotic, bargain-filled Ameyoko street market.',
          category: 'activity',
          neighborhood: 'Ueno',
          duration: 90,
          costEstimate: 15,
          tags: ['nature', 'shopping', 'local'],
          timeOfDay: 'afternoon',
        },
      ],
      eveningActivities: [
        {
          id: 'act-016',
          name: 'Yakitori Alley under the Tracks',
          description: 'Eat grilled chicken skewers at open-air stalls under the Yurakucho railway tracks — a quintessential Tokyo experience.',
          category: 'food',
          neighborhood: 'Yurakucho',
          duration: 60,
          costEstimate: 20,
          tags: ['foodie', 'local', 'budget-friendly', 'experience'],
          timeOfDay: 'evening',
        },
        {
          id: 'act-017',
          name: 'Roppongi Hills Night View',
          description: 'End your trip with skyline views from the Mori Tower observation deck as the city lights up.',
          category: 'sight',
          neighborhood: 'Roppongi',
          duration: 60,
          costEstimate: 20,
          tags: ['views', 'iconic', 'romantic'],
          timeOfDay: 'evening',
        },
      ],
      dailyBudget: 100,
    },
  ],
};
